# Read all data

sub_test = read.table("subject_test.txt", sep="\t")
sub_train = read.table("subject_train.txt", sep="\t")
x_test = read.table("X_test.txt", sep="",stringsAsFactors = FALSE)
y_test = read.table("Y_test.txt", sep="\t")
x_train = read.table("X_train.txt", sep="",stringsAsFactors = FALSE)
y_train = read.table("Y_train.txt", sep="\t")

## 1
## Merges the training and the test sets to create one data set. 

m_sub_y_x_test <- data.frame(sub_test,y_test,x_test)
m_sub_y_x_train <- data.frame(sub_train,y_train,x_train)
m_all <- rbind(m_sub_y_x_test,m_sub_y_x_train)

## 2 
## Extracts only the measurements on the mean and standard deviation for each measurement. 

m_all_2 <- data.frame(m_all$V1,m_all$V1.1,m_all$V1.2,  
m_all$V2,  
m_all$V3,  
m_all$V41, 
m_all$V42, 
m_all$V43, 
m_all$V81, 
m_all$V82, 
m_all$V83, 
m_all$V121,
m_all$V122,
m_all$V123,
m_all$V161,
m_all$V162,
m_all$V163,
m_all$V201,
m_all$V214,
m_all$V227,
m_all$V240,
m_all$V253,
m_all$V266,
m_all$V267,
m_all$V268,
m_all$V345,
m_all$V346,
m_all$V347,
m_all$V424,
m_all$V425,
m_all$V426,
m_all$V503,
m_all$V516,
m_all$V529,
m_all$V542,
m_all$V294,
m_all$V295,
m_all$V296,
m_all$V373,
m_all$V374,
m_all$V375,
m_all$V452,
m_all$V453,
m_all$V454,
m_all$V513,
m_all$V526,
m_all$V539,
m_all$V552,
m_all$V4, 
m_all$V5, 
m_all$V6, 
m_all$V44, 
m_all$V45, 
m_all$V46, 
m_all$V84, 
m_all$V85, 
m_all$V86, 
m_all$V124,
m_all$V125,
m_all$V126,
m_all$V164,
m_all$V165,
m_all$V166,
m_all$V202,
m_all$V215,
m_all$V228,
m_all$V241,
m_all$V254,
m_all$V269,
m_all$V270,
m_all$V271,
m_all$V348,
m_all$V349,
m_all$V350,
m_all$V427,
m_all$V428,
m_all$V429,
m_all$V504,
m_all$V517,
m_all$V530,
m_all$V543)



#3 and 4
## Uses descriptive activity names to name the activities in the data set
## Appropriately labels the data set with descriptive activity names. 

z1 <- y_test
for (i in 1:ncol(y_test)) z1[, i] <- recode(z1[, i], '1 = "WALKING"; 2 = "WALKING_UPSTAIRS";
		 3 = "WALKING_DOWNSTAIRS"; 4 = "SITTING" ; 5 = "STANDING" ; 6 = "LAYING"')
y_test <- z1

##########

z2 <- y_train
for (i in 1:ncol(y_train)) z2[, i] <- recode(z2[, i], '1 = "WALKING"; 2 = "WALKING_UPSTAIRS";
		 3 = "WALKING_DOWNSTAIRS"; 4 = "SITTING" ; 5 = "STANDING" ; 6 = "LAYING"')
y_train <- z2

#### 5 
## Creates a second, independent tidy data set 
## with the average of each variable for each activity and each subject. 

colnames(m_all_2) <- c("subject",
"activity",
"tBodyAcc_mean_X",
"tBodyAcc_mean_Y",
"tBodyAcc_mean_Z",
"tGravityAcc_mean_X",
"tGravityAcc_mean_Y",
"tGravityAcc_mean_Z",
"tBodyAccJerk_mean_X",
"tBodyAccJerk_mean_Y",
"tBodyAccJerk_mean_Z",
"tBodyGyro_mean_X",
"tBodyGyro_mean_Y",
"tBodyGyro_mean_Z",
"tBodyGyroJerk_mean_X",
"tBodyGyroJerk_mean_Y",
"tBodyGyroJerk_mean_Z",
"tBodyAccMag_mean",
"tGravityAccMag_mean",
"tBodyAccJerkMag_mean",
"tBodyGyroMag_mean",
"tBodyGyroJerkMag_mean",
"fBodyAcc_mean_X",
"fBodyAcc_mean_Y",
"fBodyAcc_mean_Z",
"fBodyAccJerk_mean_X",
"fBodyAccJerk_mean_Y",
"fBodyAccJerk_mean_Z",
"fBodyGyro_mean_X",
"fBodyGyro_mean_Y",
"fBodyGyro_mean_Z",
"fBodyAccMag_mean",
"fBodyBodyAccJerkMag_mean",
"fBodyBodyGyroMag_mean",
"fBodyBodyGyroJerkMag_mean",
"fBodyAcc_meanFreq_X",
"fBodyAcc_meanFreq_Y",
"fBodyAcc_meanFreq_Z",
"fBodyAccJerk_meanFreq_X",
"fBodyAccJerk_meanFreq_Y",
"fBodyAccJerk_meanFreq_Z",
"fBodyGyro_meanFreq_X",
"fBodyGyro_meanFreq_Y",
"fBodyGyro_meanFreq_Z",
"fBodyAccMag_meanFreq",
"fBodyBodyAccJerkMag_meanFreq",
"fBodyBodyGyroMag_meanFreq",
"fBodyBodyGyroJerkMag_meanFreq",
"tBodyAcc_std_X",
"tBodyAcc_std_Y",
"tBodyAcc_std_Z",
"tGravityAcc_std_X",
"tGravityAcc_std_Y",
"tGravityAcc_std_Z",
"tBodyAccJerk_std_X",
"tBodyAccJerk_std_Y",
"tBodyAccJerk_std_Z",
"tBodyGyro_std_X",
"tBodyGyro_std_Y",
"tBodyGyro_std_Z",
"tBodyGyroJerk_std_X",
"tBodyGyroJerk_std_Y",
"tBodyGyroJerk_std_Z",
"tBodyAccMag_std",
"tGravityAccMag_std",
"tBodyAccJerkMag_std",
"tBodyGyroMag_std",
"tBodyGyroJerkMag_std",
"fBodyAcc_std_X",
"fBodyAcc_std_Y",
"fBodyAcc_std_Z",
"fBodyAccJerk_std_X",
"fBodyAccJerk_std_Y",
"fBodyAccJerk_std_Z",
"fBodyGyro_std_X",
"fBodyGyro_std_Y",
"fBodyGyro_std_Z",
"fBodyAccMag_std",
"fBodyBodyAccJerkMag_std",
"fBodyBodyGyroMag_std",
"fBodyBodyGyroJerkMag_std")



## sqldf to calculate average of all columns

t <- sqldf("select distinct subject,
activity,
avg(tBodyAcc_mean_X),
avg(tBodyAcc_mean_Y),
avg(tBodyAcc_mean_Z),
avg(tGravityAcc_mean_X),
avg(tGravityAcc_mean_Y),
avg(tGravityAcc_mean_Z),
avg(tBodyAccJerk_mean_X),
avg(tBodyAccJerk_mean_Y),
avg(tBodyAccJerk_mean_Z),
avg(tBodyGyro_mean_X),
avg(tBodyGyro_mean_Y),
avg(tBodyGyro_mean_Z),
avg(tBodyGyroJerk_mean_X),
avg(tBodyGyroJerk_mean_Y),
avg(tBodyGyroJerk_mean_Z),
avg(tBodyAccMag_mean),
avg(tGravityAccMag_mean),
avg(tBodyAccJerkMag_mean),
avg(tBodyGyroMag_mean),
avg(tBodyGyroJerkMag_mean),
avg(fBodyAcc_mean_X),
avg(fBodyAcc_mean_Y),
avg(fBodyAcc_mean_Z),
avg(fBodyAccJerk_mean_X),
avg(fBodyAccJerk_mean_Y),
avg(fBodyAccJerk_mean_Z),
avg(fBodyGyro_mean_X),
avg(fBodyGyro_mean_Y),
avg(fBodyGyro_mean_Z),
avg(fBodyAccMag_mean),
avg(fBodyBodyAccJerkMag_mean),
avg(fBodyBodyGyroMag_mean),
avg(fBodyBodyGyroJerkMag_mean),
avg(fBodyAcc_meanFreq_X),
avg(fBodyAcc_meanFreq_Y),
avg(fBodyAcc_meanFreq_Z),
avg(fBodyAccJerk_meanFreq_X),
avg(fBodyAccJerk_meanFreq_Y),
avg(fBodyAccJerk_meanFreq_Z),
avg(fBodyGyro_meanFreq_X),
avg(fBodyGyro_meanFreq_Y),
avg(fBodyGyro_meanFreq_Z),
avg(fBodyAccMag_meanFreq),
avg(fBodyBodyAccJerkMag_meanFreq),
avg(fBodyBodyGyroMag_meanFreq),
avg(fBodyBodyGyroJerkMag_meanFreq),
avg(tBodyAcc_std_X),
avg(tBodyAcc_std_Y),
avg(tBodyAcc_std_Z),
avg(tGravityAcc_std_X),
avg(tGravityAcc_std_Y),
avg(tGravityAcc_std_Z),
avg(tBodyAccJerk_std_X),
avg(tBodyAccJerk_std_Y),
avg(tBodyAccJerk_std_Z),
avg(tBodyGyro_std_X),
avg(tBodyGyro_std_Y),
avg(tBodyGyro_std_Z),
avg(tBodyGyroJerk_std_X),
avg(tBodyGyroJerk_std_Y),
avg(tBodyGyroJerk_std_Z),
avg(tBodyAccMag_std),
avg(tGravityAccMag_std),
avg(tBodyAccJerkMag_std),
avg(tBodyGyroMag_std),
avg(tBodyGyroJerkMag_std),
avg(fBodyAcc_std_X),
avg(fBodyAcc_std_Y),
avg(fBodyAcc_std_Z),
avg(fBodyAccJerk_std_X),
avg(fBodyAccJerk_std_Y),
avg(fBodyAccJerk_std_Z),
avg(fBodyGyro_std_X),
avg(fBodyGyro_std_Y),
avg(fBodyGyro_std_Z),
avg(fBodyAccMag_std),
avg(fBodyBodyAccJerkMag_std),
avg(fBodyBodyGyroMag_std),
avg(fBodyBodyGyroJerkMag_std) from m_all_2 group by 1,2 order by 1,2")

# write tidy data set to file
write.table(t, "tidy_data_set.txt", sep="\t")
